nodeLinker: node-modules

packageExtensions:
  '@prisma/client@*':
    dependencies:
      .prisma: 'link:See "resolution" field of package.json'

yarnPath: .yarn/releases/yarn-3.6.4.cjs

unsafeHttpWhitelist: ['localhost']
